# from https://docs.travis-ci.com/user/languages/python/
language: python
python:
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install sympy
# command to run tests
script: BSSN/test/run_BSSN_tests.sh
